### App Info ###
info.app.version: 1.0-SNAPSHOT

## Spring modules info ##
spring:
  ### Database ###
  datasource:
    url: "jdbc:h2:file:./h2/asm-project;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE"
    driver-class-name: org.h2.Driver
    username: sa
    password:
    initialize: true
    continueOnError: true
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
  ### JPA ###
  jpa:
    ###   DDL   ###
    hibernate.ddl-auto: validate
    ## Hibernate Search
    # Specify the DirectoryProvider to use (the Lucene Directory)
    properties.hibernate.search.default:
      directory_provider: filesystem
      # Using the filesystem DirectoryProvider you also have to specify the default
      # base directory for all indexes (make sure that the application have write
      # permissions on such directory)
      indexBase: /tmp/suricate-io/suricate/lucene/indexes/
  ### Multipart configuration ###
  http.multipart:
    max-file-size: 10Mb
    max-request-size: 10Mb
  ### Mustache ###
  mustache.check-template-location: false
  ### Enable cache ###
  cache.jcache.config: classpath:ehcache3.xml

### Default error page ###
server.error.whitelabel.enabled: false

### Security ###
security.oauth2.resource.filter-order :  3

### Actuator ###
management.context-path: /manage
endpoints:
  enabled: false
  health.enabled: true
  flyway.web.enabled: true

### logging ###
## Keep this enable to see csrf issues
logging:
  file: /tmp/suricate-io/suricate/log
  level:
    io.suricate.monitoring: DEBUG
    net.sf.jmimemagic.MagicParser :  off
    org.springframework.boot.actuate: INFO
    org.springframework.security.web.csrf.CsrfFilter: DEBUG

### Encryptor ###
jasypt.encryptor:
  password:  ZAkOZ9rIJCDVk6a10
  stringOutputType:  hexadecimal

##########################################
###       Application properties       ###
##########################################
application:
  authentication:
    ### Authentication Management (ldap | database) ###
    provider: database
    ###   LDAP Authentication   ###
    ldap:
      url:
      userSearchFilter:
      firstNameAttributName:
      lastNameAttributName:
      mailAttributName:
    ### JWT Configuration ###
    jwt:
      secret:  ${random.value}
      tokenValidity:  1800
      tokenValidityRememberMe:  2592000
  ### Cors ###
  cors:
    allow-credentials:  true
    allowed-headers:  Content-Type, Accept, Authorization, X-Requested-With
    allowed-methods:  GET,POST,OPTIONS,DELETE,PUT
    allowed-origins:  "*"
    max-age:  3600
  ### SSL Properties ###
  ssl:
    ## Key store
    keyStore:
      path:
      password:
      type:
    ## Trust store
    trustStore:
      path:
      password:
      type:
  ### Widgets Repo ###
  # Widget Repo
  widgets:
    git:
      url: https://github.com/suricate-io/widgets
      branch: master
    updateEnable: true

app:
  trust-store:
  trust-store-password:

### proxy ###
#proxy.host:
#proxy.port:
#proxy.noProxyDomains: