### App Info ###
info.app.version: 1.0-SNAPSHOT

## tomcat server port
server.port: 8080

## Spring modules info ##
spring:
  ### Database ###
  datasource:
    url: "jdbc:h2:file:./h2/suricate;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE"
    driver-class-name: org.h2.Driver
    username: sa
    password:
    continueOnError: true
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
    initialization-mode: always
  ### JPA ###
  jpa:
    ###   DDL   ###
    hibernate.ddl-auto: validate
    ## Hibernate Search
    # Specify the DirectoryProvider to use (the Lucene Directory)
    properties.hibernate.search.default:
      directory_provider: filesystem
      # Using the filesystem DirectoryProvider you also have to specify the default
      # base directory for all indexes (make sure that the application have write
      # permissions on such directory)
      indexBase: /tmp/suricate-io/suricate/lucene/indexes/
  ### Mustache ###
  mustache.check-template-location: false
  ### Enable cache ###
  cache.jcache.config: classpath:ehcache3.xml
  ### Servlet
  servlet:
    multipart:
      max-file-size: 10Mb
      max-request-size: 10Mb

### Default error page ###
server.error.whitelabel.enabled: false

### Security ###
security.oauth2:
  client:
    client-id: suricateAngular
    client-secret: suricateAngularSecret
  resource.filter-order :  3

### Actuator ###
management:
  endpoints:
    health.enabled: true
    flyway.web.enabled: true
    configprops;enabled: true
    enabled-by-default: false
    jmx:
      exposure:
        include: env
        exclude: beans
    web:
      exposure:
        include: configprops
  server:
    servlet:
      context-path: /api/manage



### logging ###
## Keep this enable to see csrf issues
logging:
  file: /tmp/suricate-io/suricate/log
  level:
    io.suricate.monitoring: DEBUG
    net.sf.jmimemagic.MagicParser :  off
    org.springframework.boot.actuate: INFO
    org.springframework.security.web.csrf.CsrfFilter: DEBUG

### Encryptor ###
jasypt.encryptor:
  password:  ZAkOZ9rIJCDVk6a10
  stringOutputType:  hexadecimal

##########################################
###       Application properties       ###
##########################################
application:
  authentication:
    ### Authentication Management (ldap | database) ###
    provider: database
    ###   LDAP Authentication   ###
    ldap:
      url:
      userSearchFilter:
      firstNameAttributName:
      lastNameAttributName:
      mailAttributName:
    ### JWT Configuration ###
    jwt:
      secret:  ${random.value}
      tokenValidity:  1800
      tokenValidityRememberMe:  2592000
  ### Cors ###
  cors:
    allow-credentials:  true
    allowed-headers:  Content-Type, Accept, Authorization, X-Requested-With
    allowed-methods:  GET,POST,OPTIONS,DELETE,PUT
    allowed-origins:  "*"
    max-age:  3600
  ### OAuth ###
  oauth:
    client: suricateAngular
    secret: suricateAngularSecret
  ### SSL Properties ###
  ssl:
    ## Key store
    keyStore:
      path:
      password:
      type:
    ## Trust store
    trustStore:
      path:
      password:
      type:
  ### Widgets Repo ###
  # Widget Repo
  widgets:
    git:
      url: https://github.com/suricate-io/widgets
      branch: master
    updateEnable: true
  ### Swagger Springfox properties ###
  swagger:
    title: Suricate API
    description: Rest API for integrating with backend layer.
    version: 1.0
    termsOfServiceUrl:
    license: Apache 2.0
    licenseUrl: http://www.apache.org/licenses/LICENSE-2.0.html
    groupName: suricate-api
    protocols: http,https
    defaultIncludePattern: /api/.*
    contactName: Suricate-io
    contactUrl: https://github.com/suricate-io/suricate
    contactEmail:

### proxy ###
#proxy.host: ptx.proxy.corp.sopra
#proxy.port: 8080
#proxy.noProxyDomains:
